name: Publish Action

on: 
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: macos-latest
    env:
      working-directory: ./multiplatform
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: '11'
    - name: Publish artifacts
      env:
        GITHUB_USERNAME: "Github Action"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        version=${GITHUB_REF/refs\/tags\//}
        echo "Version: $version"
        ../gradlew -Pversion=${version} publish
      working-directory: ${{env.working-directory}}
